/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        TestCases tests = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here

        ////INTV-1/Session-6/2/Automate_count_hyperlinks
        //tests.TC_CountHyperlinks();

        ////INTV-1/Session-6/4/Automate_google_name_links
        tests.TC_GoogleNameLinks();

        
        //tests.testCase01();
        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
